server:
  port: 8082


spring:
  application:
#    name: cloud-app-two
    name: cloud-app-cluster

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
service-url: cloud-spring-shiro